#!/bin/sh

# color
Red="\033[3;31m"
Red_White="\033[1;41m"
Reset="\033[1;0m"
Cyan="\033[2;36m"
Blink="\e[5m"
Blod="\e[1m"
Green="\033[2;32m"
White="\033[2;37m"
Yellow="\033[1;33m"

Success="\t\t${White}[   ${Green}${Blink}OK${Reset}   ${White}]${Reset}"
Failed="\t\t${White}[ ${Reset}${Red}${Blink}Failed${Reset}${White} ]${Reset}"

default_path="/usr/local/src/apm"

apache_path="/usr/local/src/apm/apache"

php_path="/usr/local/src/apm/php"

mysql_path="/usr/local/src/apm/mysql"
